
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-dining-s26-06
owner: ucsb-cs156-s26
repo_name: proj-dining-s26-06
pull_requests: [{"author":{"id":"U_kgDOCeSMMQ","is_bot":false,"login":"brandt465","name":""},"headRefName":"ev-implement-toggleable-roles","number":28,"title":"Ev implement toggleable roles","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/28"},{"author":{"id":"U_kgDOCNiujA","is_bot":false,"login":"prishabobde","name":""},"headRefName":"pb-add_moderator_comments_modal","number":27,"title":"pb - added moderator comments modal","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/27"},{"author":{"id":"MDQ6VXNlcjY4MDk3OTY3","is_bot":false,"login":"roy-lee7473","name":"Roy Lee"},"headRefName":"rl-reintroduce-eslint","number":26,"title":"rl - reintroduced react eslint rules","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/26"},{"author":{"id":"U_kgDOCu9WdA","is_bot":false,"login":"Chaehana","name":""},"headRefName":"cb-add-moderator-backend","number":25,"title":"cb-connected backend for moderator endpoint","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/25"}]
