
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-dining-s26-06
owner: ucsb-cs156-s26
repo_name: proj-dining-s26-06
pull_requests: [{"author":{"id":"U_kgDOCu9WdA","is_bot":false,"login":"Chaehana","name":""},"headRefName":"cb-moderator-alias-table","number":37,"title":"Cb moderator alias table","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/37"},{"author":{"id":"U_kgDOCVG5mA","is_bot":false,"login":"dongyi-xia","name":""},"headRefName":"dx-improve-integration-test-time","number":36,"title":"dx - Improve integration test start time","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/36"},{"author":{"id":"U_kgDOCu9WdA","is_bot":false,"login":"Chaehana","name":""},"headRefName":"cb-moderator-review-table","number":34,"title":"cb - updated moderate review table","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/34"},{"author":{"id":"U_kgDOCVG5mA","is_bot":false,"login":"dongyi-xia","name":""},"headRefName":"dx-review-edit","number":29,"title":"dx - implement review edit page","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/29"},{"author":{"id":"U_kgDOCeSMMQ","is_bot":false,"login":"brandt465","name":""},"headRefName":"ev-implement-toggleable-roles","number":28,"title":"Ev implement toggleable roles","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/28"},{"author":{"id":"U_kgDOCNiujA","is_bot":false,"login":"prishabobde","name":""},"headRefName":"pb-add_moderator_comments_modal","number":27,"title":"pb - added moderator comments modal","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-06/pull/27"}]
